name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Maven Verify
        run: mvn -B clean verify

      - name: Test Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RSYNC_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.RSYNC_SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy
  #       run: rsync -avzP -e ssh ${{ secrets.TOMCAT_SSH_LOGIN }}@${{ secrets.RSYNC_SSH_HOST }}:/webapps ./
#        uses: appleboy/ssh-action@master
#         run: rsync -avz ${{ github.workspace }}/target/cicd.war ${{ secrets.TOMCAT_SSH_LOGIN }}@${{ secrets.RSYNC_SSH_HOST }}:/home/avada/web/kino.avada-media-dev1.od.ua/webapps
        run: scp ${{ github.workspace }}/target/cicd.war v@${{ secrets.RSYNC_SSH_HOST }}:/home/avada/web/kino.avada-media-dev1.od.ua/webapps
#      run: curl -v -u  ${{ secrets.TOMCAT_SSH_LOGIN }}:${{ secrets.TOMCAT_PASSWORD }} -T /home/runner/work/ci-cd/ci-cd/target/cicd.war 'kino.avada-media-dev1.od.ua//manager/text/deploy?path=/cicd'
